### ISSUE TITLE
Databases 

### ISSUE THREAD

**Issue by at-annguyen** [AT-PHPIntership/book-library#10]
![library_books](https://user-images.githubusercontent.com/26828657/34513474-08a56e00-f09b-11e7-962e-83344c406948.png)

**Comment by at-duyho** [comment]
- trong table donator có cần thiết phải có column **employee_code** và **email**?
- check lại size của trường access_token, sẽ có trường hợp > 45
- expries_at: sửa lại tên cho đúng ý nghĩa. Type nên là date không nên là varchar
- có cần thiết table donator không?

**Comment by at-annguyen** [comment]
- cần có employee_code và email vì có thể có thành viên chưa đăng nhập vào thì chưa lưa employee_code và chưa có user_id
-
- expires_at là field trả về trong portal với  type date thì không save được 'UTC'  
- theo em là có ạ

**Comment by at-duyho** [comment]
- Trong trường hợp user chưa đăng nhập, thông tin sẽ được lấy từ đâu để lưu vào table donator?( user_id sẽ lấy từ đâu, khi nó là khoá ngoại của table?)
- Json trả về từ portal thì mặc định là string rồi, task của mình là convert nó qua đúng kiểu để mình xử lý cho đơn giản. tên trường anh thấy chưa hợp lý, không có ý nghĩa.

**Comment by at-annguyen** [comment]
- user_id em cho phép nullable để nếu k có thì mình sẽ nhập mã nhân viên và email vô để chắc chắn
- nhưng mà khi lưu vô db mà để type kiểu date thì hắn sẽ báo lỗi anh. convert qua thì hắn vẫn còn UTC vì thế e nghĩ để varchar để lưu tránh bug. còn tên thì em lấy đúng như theo portal thôi chứ em cũng chẳng hiểu expires_at ni để làm gì ạ

**Comment by at-duyho** [comment]
- nếu user_id cho phép nullable thì anh nghĩ nên disscust với mọi người có nên tách riêng bảng donator ra, không liên quan j đến table user.
- convert đúng kiểu(có thể là date, timestamp, datetime) và lưu xuống sẽ không báo lỗi đâu em. Còn lỗi như thế nào thì export rồi gởi qua cho anh.
